import type { NativeCursorType } from "@/native/contracts";

/**
 * A single themed cursor image override for one {@link NativeCursorType}.
 *
 * width/height/hotspot are in the same ~32-logical-pixel reference as the built-in
 * PRETTY_NATIVE_CURSOR_ASSETS, so a theme asset matches the default cursor's on-screen
 * size regardless of source PNG resolution. The PNG can be higher-res (e.g. 128x128)
 * and is downscaled at draw time for crisper retina output.
 */
export interface CursorThemeAsset {
	/** Path relative to the public asset root, e.g. "cursors/<id>/arrow.png". */
	assetPath: string;
	width: number;
	height: number;
	hotspotX: number;
	hotspotY: number;
	/** Face and grayscale relief map for the optional modelled cursor. Hotspots use the same
	 *  32-logical-pixel reference as the flat asset above. */
	model3d?: {
		assetPath: string;
		depthPath: string;
		hotspotX: number;
		hotspotY: number;
	};
}

export interface CursorTheme {
	id: string;
	/** Display label. Proper nouns, so not run through i18n. */
	name: string;
	/** Attribution / origin for the artwork. */
	source?: string;
	/**
	 * Per-cursor-type overrides. Missing types fall back to the built-in default art,
	 * so a pack that only ships "arrow" and "pointer" is complete.
	 */
	assets: Partial<Record<NativeCursorType, CursorThemeAsset>>;
}

/** Sentinel id for the built-in cursor art (no theme override). */
export const DEFAULT_CURSOR_THEME_ID = "default";

/**
 * One sprite as the native compositor consumes it: a path under the public asset root,
 * plus the hotspot as a 0..1 fraction OF THAT IMAGE.
 *
 * The fraction is the whole point of the contract. The compositor scales the sprite to
 * the cursor-size setting, so an offset expressed in the source image's pixels would have
 * to be rescaled at draw time; a fraction survives any scale untouched. Getting this wrong
 * is what made an enlarged cursor drift further and further from what it points at.
 */
export interface CursorSprite {
	/** Path relative to the public asset root, e.g. "cursors/default/arrow.png". */
	assetPath: string;
	/** Hotspot as a fraction of the image width / height. */
	hotspotX: number;
	hotspotY: number;
	/** Optional per-pixel top-surface height map used by the 3D cursor model. */
	modelDepthPath?: string;
}

/**
 * The built-in cursor art, rasterized from src/assets/cursors/*.svg — the native
 * compositor decodes png/jpeg from disk and cannot read those SVGs (they only exist as
 * bundler URLs in the renderer).
 *
 * Generated by scripts/generate-default-cursor-sprites.mjs; regenerate it rather than
 * hand-editing, so the PNGs and these hotspots can't drift apart.
 */
export const DEFAULT_CURSOR_SPRITES: Record<NativeCursorType, CursorSprite> = {
	arrow: { assetPath: "cursors/default/arrow.png", hotspotX: 0.1205, hotspotY: 0.0881 },
	text: { assetPath: "cursors/default/text.png", hotspotX: 0.4355, hotspotY: 0.5369 },
	pointer: { assetPath: "cursors/default/pointer.png", hotspotX: 0.3874, hotspotY: 0.0032 },
	crosshair: { assetPath: "cursors/default/crosshair.png", hotspotX: 0.4667, hotspotY: 0.4667 },
	"open-hand": { assetPath: "cursors/default/open-hand.png", hotspotX: 0.4375, hotspotY: 0.1724 },
	"closed-hand": {
		assetPath: "cursors/default/closed-hand.png",
		hotspotX: 0.3889,
		hotspotY: 0.4455,
	},
	"resize-ew": { assetPath: "cursors/default/resize-ew.png", hotspotX: 0.485, hotspotY: 0.4706 },
	"resize-ns": { assetPath: "cursors/default/resize-ns.png", hotspotX: 0.5, hotspotY: 0.5 },
	"resize-nesw": { assetPath: "cursors/default/resize-nesw.png", hotspotX: 0.5, hotspotY: 0.5 },
	"resize-nwse": { assetPath: "cursors/default/resize-nwse.png", hotspotX: 0.5, hotspotY: 0.5 },
	move: { assetPath: "cursors/default/move.png", hotspotX: 0.4437, hotspotY: 0.4437 },
	"not-allowed": { assetPath: "cursors/default/not-allowed.png", hotspotX: 0.5, hotspotY: 0.5 },
	wait: { assetPath: "cursors/default/wait.png", hotspotX: 0.5, hotspotY: 0.5 },
	"app-starting": {
		assetPath: "cursors/default/app-starting.png",
		hotspotX: 0.05,
		hotspotY: 0.0537,
	},
	help: { assetPath: "cursors/default/help.png", hotspotX: 0.0515, hotspotY: 0.0572 },
	"up-arrow": { assetPath: "cursors/default/up-arrow.png", hotspotX: 0.5, hotspotY: 0.069 },
};

/**
 * Bundled cursor themes. These five packs are original OpenScreen artwork. Their raster
 * masters live in design/cursors/ and are prepared by scripts/generate-original-cursor-themes.mjs.
 * The former Sweezy packs were removed
 * because their terms forbid redistribution without written permission.
 *
 * To add one: drop arrow.png/pointer.png into public/cursors/<id>/ and add an entry here
 * with hotspots normalized to the 32-logical reference (divide a 128px-pack hotspot by 4).
 * Add a model3d face and depth map when the theme has its own 3D treatment. An id that leaves this list reads back as the default art
 * through `normalizeCursorThemeId`, so a project saved with it still opens.
 */
export const CURSOR_THEMES: readonly CursorTheme[] = [
	{
		id: "studio-ink",
		name: "Studio Ink",
		assets: {
			arrow: {
				assetPath: "cursors/studio-ink/arrow.png",
				width: 32,
				height: 32,
				hotspotX: 6.2304,
				hotspotY: 2.0992,
				model3d: {
					assetPath: "cursors/studio-ink/model-arrow.png",
					depthPath: "cursors/studio-ink/model-arrow-depth.png",
					hotspotX: 6.3264,
					hotspotY: 2.032,
				},
			},
			pointer: {
				assetPath: "cursors/studio-ink/pointer.png",
				width: 32,
				height: 32,
				hotspotX: 12.848,
				hotspotY: 2.0704,
				model3d: {
					assetPath: "cursors/studio-ink/model-pointer.png",
					depthPath: "cursors/studio-ink/model-pointer-depth.png",
					hotspotX: 12.2304,
					hotspotY: 1.9232,
				},
			},
		},
	},
	{
		id: "prism-glow",
		name: "Prism Glow",
		assets: {
			arrow: {
				assetPath: "cursors/prism-glow/arrow.png",
				width: 32,
				height: 32,
				hotspotX: 6.3456,
				hotspotY: 2.0672,
				model3d: {
					assetPath: "cursors/prism-glow/model-arrow.png",
					depthPath: "cursors/prism-glow/model-arrow-depth.png",
					hotspotX: 6.5728,
					hotspotY: 1.9296,
				},
			},
			pointer: {
				assetPath: "cursors/prism-glow/pointer.png",
				width: 32,
				height: 32,
				hotspotX: 11.968,
				hotspotY: 2.0352,
				model3d: {
					assetPath: "cursors/prism-glow/model-pointer.png",
					depthPath: "cursors/prism-glow/model-pointer-depth.png",
					hotspotX: 11.4816,
					hotspotY: 2.0,
				},
			},
		},
	},
	{
		id: "pop-coral",
		name: "Pop Coral",
		assets: {
			arrow: {
				assetPath: "cursors/pop-coral/arrow.png",
				width: 32,
				height: 32,
				hotspotX: 10.4768,
				hotspotY: 2.1792,
				model3d: {
					assetPath: "cursors/pop-coral/model-arrow.png",
					depthPath: "cursors/pop-coral/model-arrow-depth.png",
					hotspotX: 7.2224,
					hotspotY: 1.9648,
				},
			},
			pointer: {
				assetPath: "cursors/pop-coral/pointer.png",
				width: 32,
				height: 32,
				hotspotX: 12.3456,
				hotspotY: 2,
				model3d: {
					assetPath: "cursors/pop-coral/model-pointer.png",
					depthPath: "cursors/pop-coral/model-pointer-depth.png",
					hotspotX: 12.1152,
					hotspotY: 1.9616,
				},
			},
		},
	},
	{
		id: "pixel-candy",
		name: "Pixel Candy",
		assets: {
			arrow: {
				assetPath: "cursors/pixel-candy/arrow.png",
				width: 32,
				height: 32,
				hotspotX: 7.3664,
				hotspotY: 2,
				model3d: {
					assetPath: "cursors/pixel-candy/model-arrow.png",
					depthPath: "cursors/pixel-candy/model-arrow-depth.png",
					hotspotX: 7.8176,
					hotspotY: 1.9616,
				},
			},
			pointer: {
				assetPath: "cursors/pixel-candy/pointer.png",
				width: 32,
				height: 32,
				hotspotX: 13.376,
				hotspotY: 1.9264,
				model3d: {
					assetPath: "cursors/pixel-candy/model-pointer.png",
					depthPath: "cursors/pixel-candy/model-pointer-depth.png",
					hotspotX: 13.6256,
					hotspotY: 1.92,
				},
			},
		},
	},
	{
		id: "star-sprout",
		name: "Star Sprout",
		assets: {
			arrow: {
				assetPath: "cursors/star-sprout/arrow.png",
				width: 32,
				height: 32,
				hotspotX: 4.7232,
				hotspotY: 2.1152,
				model3d: {
					assetPath: "cursors/star-sprout/model-arrow.png",
					depthPath: "cursors/star-sprout/model-arrow-depth.png",
					hotspotX: 3.7824,
					hotspotY: 1.9136,
				},
			},
			pointer: {
				assetPath: "cursors/star-sprout/pointer.png",
				width: 32,
				height: 32,
				hotspotX: 13.1712,
				hotspotY: 2.0384,
				model3d: {
					assetPath: "cursors/star-sprout/model-pointer.png",
					depthPath: "cursors/star-sprout/model-pointer-depth.png",
					hotspotX: 12.8352,
					hotspotY: 2.0,
				},
			},
		},
	},
];

/** All selectable theme ids, including the built-in default. */
export const CURSOR_THEME_IDS: ReadonlySet<string> = new Set([
	DEFAULT_CURSOR_THEME_ID,
	...CURSOR_THEMES.map((theme) => theme.id),
]);

/**
 * Paths the theme picker should show. `pointer` is set only when that artwork
 * differs from `arrow`, so a pack with its own hand is not previewed as arrow-only.
 */
export function themePickerPreviewAssets(theme: CursorTheme | null): {
	arrow: string;
	pointer: string | null;
} {
	if (!theme) {
		const arrow = DEFAULT_CURSOR_SPRITES.arrow.assetPath;
		const pointer = DEFAULT_CURSOR_SPRITES.pointer.assetPath;
		return { arrow, pointer: pointer !== arrow ? pointer : null };
	}
	const arrow = theme.assets.arrow?.assetPath ?? theme.assets.pointer?.assetPath ?? "";
	const pointer = theme.assets.pointer?.assetPath ?? null;
	return { arrow, pointer: pointer && pointer !== arrow ? pointer : null };
}

/** Returns the theme for `id`, or null for the default / unknown ids. */
export function getCursorTheme(id: string | null | undefined): CursorTheme | null {
	if (!id || id === DEFAULT_CURSOR_THEME_ID) {
		return null;
	}
	return CURSOR_THEMES.find((theme) => theme.id === id) ?? null;
}

/**
 * Normalizes a persisted/incoming theme id to a known value, falling back to the
 * default for anything unrecognized.
 */
export function normalizeCursorThemeId(id: unknown): string {
	return typeof id === "string" && CURSOR_THEME_IDS.has(id) ? id : DEFAULT_CURSOR_THEME_ID;
}

/**
 * The full sprite set for a theme: its own art where it has any, the built-in art for
 * every other cursor state.
 *
 * A pack may ship only an arrow and a pointer, but a recording moves through a dozen OS
 * states — text, resize, wait, grab. Serving the theme's arrow for all of them (what the
 * native path used to do) shows a resize handle as an arrow; serving nothing shows a
 * placeholder. Mixing in the built-in art per state keeps the pointer honest about what
 * the user was doing, and a pack that later adds a text.png slots straight in.
 */
export function resolveCursorSprites(
	themeId: string | null | undefined,
	alwaysArrow = false,
	model3d = false,
): Record<NativeCursorType, CursorSprite> {
	const sprites = { ...DEFAULT_CURSOR_SPRITES };
	for (const [type, asset] of Object.entries(getCursorTheme(themeId)?.assets ?? {})) {
		if (asset.width <= 0 || asset.height <= 0) {
			continue;
		}
		sprites[type as NativeCursorType] = {
			assetPath: model3d && asset.model3d ? asset.model3d.assetPath : asset.assetPath,
			// Theme hotspots are authored against the asset's own 32-logical reference;
			// the contract is a fraction of the image. See CursorSprite.
			hotspotX: (model3d && asset.model3d ? asset.model3d.hotspotX : asset.hotspotX) / asset.width,
			hotspotY: (model3d && asset.model3d ? asset.model3d.hotspotY : asset.hotspotY) / asset.height,
			...(model3d && asset.model3d ? { modelDepthPath: asset.model3d.depthPath } : {}),
		};
	}
	// "Always use arrow": one consistent pointer for the whole recording, the I-beam and the
	// hand included. Done on the table the compositor reads, so it needs no mode of its own.
	if (alwaysArrow) {
		for (const type of Object.keys(sprites) as NativeCursorType[]) {
			sprites[type] = sprites.arrow;
		}
	}
	return sprites;
}
